spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SaintAmeN/spring-cloud-configuration.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
