spring:
  cloud:
    config:
      server:
        git:
          uri: http://bitbucket.aps-drones.com:7990/scm/ass/configuration.git
          username: servicesaps
          password: namstrzelacniekazano

eureka:
  client:
    serviceUrl:
      defaultZone: http://aps-platform:18010/eureka/
